% in compiler.P

% CLASSICAL CONJUNCTION WITH VALIDITY EXTENSION
event2tr_transformation([eventClause(Label,Head,andf(I1,I2))|T],TRRules):-
    validity_extension(on),
        FirstClause = trClause(Label,event(I1,[T1_rule1,T2_rule1]),
        seqf(not_etr_dbf(Label,
            goal(event(I1),event(I2,[_,_]),event(Head))),
        etr_insf(Label,
            goal(event(I2),event(I1,[T1_rule1,T2_rule1]),
            event(Head))))),
        FirstClauseExtension = trClause(Label,event(extended(I1),[T1_ext_rule1,T2_ext_rule1]),
        seqf(not_etr_dbf(Label,
            goal(event(I1),event(I2,[_,_]),event(Head))),
        etr_insf(Label,
            goal(event(I2),event(I1,[T1_ext_rule1,T2_ext_rule1]),
            event(Head))))),
    SecondClause = trClause(Label,event(I1,[T3_rule2,T4_rule2]),
        seqf(etr_dbf(Label,
            goal(event(I1),event(I2,[T1_rule2,T2_rule2]),
            event(Head))),
        seqf(min(T1_rule2,T3_rule2,T0_rule2),
        seqf(max(T2_rule2,T4_rule2,T5_rule2),
        seqf( check_event_rule_conditions(Label,Head,
                [T0_rule2,T5_rule2]),
            event(Head,[T0_rule2,T5_rule2])))))),
    SecondClauseExtension = trClause(Label,event(extended(I1),[T3_ext_rule2,T4_ext_rule2]),
        seqf(etr_dbf(Label,
            goal(event(I1),event(I2,[T1_ext_rule2,T2_ext_rule2]),
            event(Head))),
        seqf(min(T1_ext_rule2,T3_ext_rule2,T0_ext_rule2),
        seqf(max(T2_ext_rule2,T4_ext_rule2,T5_ext_rule2),
        seqf( check_event_rule_conditions(Label,Head,
                [T0_ext_rule2,T5_ext_rule2]),
            event(Head,[T0_ext_rule2,T5_ext_rule2])))))),
    ThirdClause = trClause(Label,event(I2,[T1_rule3,T2_rule3]),
        seqf(not_etr_dbf(Label,
            goal(event(I2),event(I1,[_,_]),event(Head))),
        etr_insf(Label,
            goal(event(I1),event(I2,[T1_rule3,T2_rule3]),
            event(Head))))),
    ThirdClauseExtension = trClause(Label,event(extended(I2),[T1_ext_rule3,T2_ext_rule3]),
        seqf(not_etr_dbf(Label,
            goal(event(I2),event(I1,[_,_]),event(Head))),
        etr_insf(Label,
            goal(event(I1),event(I2,[T1_ext_rule3,T2_ext_rule3]),
            event(Head))))),
    FourthClause = trClause(Label,event(I2,[T3_rule4,T4_rule4]),
        seqf(etr_dbf(Label,
            goal(event(I2),event(I1,[T1_rule4,T2_rule4]),
            event(Head))),
        seqf(min(T1_rule4,T3_rule4,T0_rule4),
        seqf(max(T2_rule4,T4_rule4,T5_rule4),
        seqf( check_event_rule_conditions(Label,Head,
                [T0_rule4,T5_rule4]),
            event(Head,[T0_rule4,T5_rule4])))))),
    FourthClauseExtension = trClause(Label,event(extended(I2),[T3_ext_rule4,T4_ext_rule4]),
        seqf(etr_dbf(Label,
            goal(event(I2),event(I1,[T1_ext_rule4,T2_ext_rule4]),
            event(Head))),
        seqf(min(T1_ext_rule4,T3_ext_rule4,T0_ext_rule4),
        seqf(max(T2_ext_rule4,T4_ext_rule4,T5_ext_rule4),
        seqf( check_event_rule_conditions(Label,Head,
                [T0_ext_rule4,T5_ext_rule4]),
            event(Head,[T0_ext_rule4,T5_ext_rule4])))))),
    FifthClauseExtension = trClause(Label,event(extended(I1),[T1_extended,T2_extended]),
    seqf(etr_dbf(Label,goal(event(I2),event(I1,[T1_extended,T2_prev]),
      event(Head))),
      seqf(less(T2_prev,T2_extended),
      seqf(etr_delf(Label,goal(event(I2),event(I1,[T1_extended,T2_prev]),
      event(Head))),
      etr_insf(Label,
            goal(event(I2),event(I1,[T1_extended,T2_extended]),
            event(Head))))))),
    SixthClauseExtension = trClause(Label,event(extended(I2),[T3_extended,T4_extended]),
    seqf(etr_dbf(Label,goal(event(I1),event(I2,[T3_extended,T4_prev]),
    event(Head))),
    seqf(less(T4_prev,T4_extended),
    seqf(etr_delf(Label,goal(event(I1),event(I2,[T3_extended,T4_prev]),
    event(Head))),
    etr_insf(Label,
            goal(event(I1),event(I2,[T3_extended,T4_extended]),
            event(Head))))))),
    event2tr_transformation(T,RestTRRules),
    TRRules =[FirstClause,FirstClauseExtension,ThirdClause,ThirdClauseExtension,
      SecondClause,SecondClauseExtension,FourthClause,FourthClauseExtension,
      FifthClauseExtension,SixthClauseExtension|
      RestTRRules],
  !.


% CONCURRENCY WITH VALIDITY EXTENSION
event2tr_transformation([eventClause(Label,Head,parf(I1,I2))|T],
    TRRules):-
  validity_extension(on),
  FirstClause = trClause(Label,event(I1,[T1_rule1,T2_rule1]),
    seqf(not_etr_dbf(Label,
      goal(event(I1),event(I2,[_,_]),event(Head))),
    etr_insf(Label,goal(event(I2),
      event(I1,[T1_rule1,T2_rule1]),
      event(Head))))),
  SecondClause = trClause(Label,event(I1,[T3_rule2,T4_rule2]),
    seqf(etr_dbf(Label,goal(event(I1),
      event(I2,[T1_rule2,T2_rule2]),
      event(Head))),
    seqf(less(T3_rule2,T2_rule2),
    seqf(min(T1_rule2,T3_rule2,T0_rule2),
    seqf(max(T2_rule2,T4_rule2,T5_rule2),
    seqf( check_event_rule_conditions(Label,Head,
        [T0_rule2,T5_rule2]),
    event(Head,[T0_rule2,T5_rule2]) )))))),
  FifthClauseExtension = trClause(Label,
    event(extended(I1),[T1_extended,T2_extended]),
      seqf(etr_dbf(Label,goal(event(I2),
        event(I1,[T1_extended,T2_prev]),
        event(Head))),
    seqf(less(T2_prev,T2_extended),
    seqf(etr_delf(Label,
      goal(event(I2),event(I1,[T1_extended,T2_prev]),
      event(Head))),
      etr_insf(Label,
            goal(event(I2),event(I1,[T1_extended,T2_extended]),
            event(Head))))))),
  ThirdClause = trClause(Label,event(I2,[T1_rule3,T2_rule3]),
    seqf(not_etr_dbf(Label,
      goal(event(I2),event(I1,[_,_]),event(Head))),
    etr_insf(Label,
      goal(event(I1),event(I2,[T1_rule3,T2_rule3]),
      event(Head))))),
  FourthClause = trClause(Label,event(I2,[T3_rule4,T4_rule4]),
    seqf(etr_dbf(Label,
      goal(event(I2),event(I1,[T1_rule4,T2_rule4]),
      event(Head))),
    seqf(less(T3_rule4,T2_rule4),
    seqf(min(T1_rule4,T3_rule4,T0_rule4),
    seqf(max(T2_rule4,T4_rule4,T5_rule4),
    seqf( check_event_rule_conditions(Label,Head,
        [T0_rule4,T5_rule4]),
      event(Head,[T0_rule4,T5_rule4]))))))),
  SixthClauseExtension = trClause(Label,
    event(extended(I2),[T3_extended,T4_extended]),
      seqf(etr_dbf(Label,goal(event(I1),
        event(I2,[T3_extended,T4_prev]),
        event(Head))),
      seqf(less(T4_prev,T4_extended),
    seqf(etr_delf(Label,
      goal(event(I1),event(I2,[T3_extended,T4_prev]),
      event(Head))),
    etr_insf(Label,
            goal(event(I1),event(I2,[T3_extended,T4_extended]),
            event(Head))))))),
  event2tr_transformation(T,RestTRRules),
  TRRules=[FirstClause,ThirdClause,SecondClause,FourthClause,
    FifthClauseExtension,SixthClauseExtension|RestTRRules],
  !.